platform :ios, '5.0'
pod 'AFNetworking', '~> 1.3.2'
pod 'SBJson', '~> 3.2.0'
pod 'ISMethodSwizzling', :git => 'https://github.com/ishkawa/ISMethodSwizzling.git'
pod 'NJKWebViewProgress', :git => 'https://github.com/ninjinkun/NJKWebViewProgress.git'